services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_USER: "guest"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "tender_management"
    depends_on:
      - db


  db:
    image: postgres:14
    environment:
      POSTGRES_DB: "tender_management"
      POSTGRES_USER: "guest"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres
    entrypoint:
      - bash
      - -c
      - |
        docker-entrypoint.sh postgres &&
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

volumes:
  postgres_data:
